cargo-features = ["codegen-backend"]

[package]
description = "An HTTP server using HTTP basic auth to make secure calls to nsupdate"
name = "webnsupdate"
version = "0.3.0-dev"
edition = "2021"

[dependencies]
axum = "0.7"
axum-auth = { version = "0.7", default-features = false, features = [
  "auth-basic",
] }
axum-client-ip = "0.6"
base64 = "0.22"
clap = { version = "4", features = ["derive", "env"] }
clap-verbosity-flag = "2"
http = "1"
miette = { version = "7", features = ["fancy"] }
ring = { version = "0.17", features = ["std"] }
tokio = { version = "1", features = [
  "macros",
  "rt",
  "process",
  "io-util",
] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[dev-dependencies]
insta = "1"

[profile.dev]
debug = 0
codegen-backend = "cranelift"
