cargo-features = ["codegen-backend"]
[package]
description = "An HTTP server using HTTP basic auth to make secure calls to nsupdate"
name = "webnsupdate"
version = "0.3.0-dev"
edition = "2021"

[dependencies]
axum = "0.7.5"
axum-client-ip = "0.6.0"
base64 = "0.22.1"
clap = { version = "4.5.4", features = ["derive", "env"] }
http = "1.1.0"
insta = "1.38.0"
miette = { version = "7.2.0", features = ["fancy"] }
ring = { version = "0.17.8", features = ["std"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

[dependencies.axum-auth]
version = "0.7.0"
default-features = false
features = ["auth-basic"]

[dependencies.tokio]
version = "1.37.0"
features = ["macros", "rt", "process", "io-util"]

[profile.dev]
debug = 0
codegen-backend = "cranelift"
