on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: nixos
    outputs:
      outPath: ${{ steps.build.outputs.outPath }}
    steps:
      - uses: https://git.salame.cl/actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - run: nix --version
      - name: Build Package
        id: build
        run: |
          outPath=$(nix build --print-build-logs --print-out-paths .#)
          echo "outPath=packages:webnsupdate:$outPath" >> "$FORGEJO_OUTPUT"
  checks:
    runs-on: nixos
    needs: build # we use the built binaries in the checks
    strategy:
      matrix:
        system:
          - x86_64-linux
        test:
          - treefmt
          - clippy
          - deny
          - nextest
          - module-ipv4-only-test
          - module-ipv4-test
          - module-ipv6-only-test
          - module-ipv6-test
          - module-nginx-test
    env:
      TEST: ${{ matrix.test }}
      SYSTEM: ${{ matrix.system }}
    steps:
      - uses: https://git.salame.cl/actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - run: nix --version
      - name: Run tests
        run: |
          nix build --print-build-logs \
            .#checks."$SYSTEM"."$TEST"
  trigger-release:
    runs-on: nixos
    needs: checks
    steps:
      - uses: https://git.salame.cl/actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0 # fetch full history (needed for changelog)
          ref: ${{ forge.head_ref }} # checkout the branch instead of the pull request ref
          token: ${{ secrets.RELEASE_TOKEN }} # use the release token so we can trigger actions
      - run: nix --version
      - name: Create release PR
        env:
          GIT_TOKEN: "${{ secrets.RELEASE_TOKEN }}" # Token to create the release
          CARGO_REGISTRY_GIT_SALAME_CL_TOKEN: "Bearer ${{ secrets.RELEASE_TOKEN }}" # Token to publish the package
          RUSTC_BOOTSTRAP: 1 # v0.3.6 uses nightly cargo features
        run: |
          nix develop .#release --command release-script
  report-size:
    runs-on: nixos
    needs: build
    steps:
      - uses: https://git.salame.cl/actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - run: nix --version
      - name: Generate size report
        uses: "https://git.salame.cl/jalil/nix-flake-outputs-size@7a01dbeb0b8892cef331fc99995f3e554487c51b" # main
        with:
          comment-on-pr: ${{ github.ref_name != 'main' }}
          generate-artifact: ${{ github.ref_name == 'main' }}
          do-comparison: true
          job-name: report-size
          prebuilt-derivations: "${{ needs.build.outputs.outPath }}"
