on: [push]
jobs:
  build:
    runs-on: nixos
    steps:
      - uses: https://git.salame.cl/actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - run: nix --version
      - name: Build Package
        run: |
          nix build --print-build-logs .#
  checks:
    needs: build # we use the built binaries in the checks
    runs-on: nixos
    strategy:
      matrix:
        system:
          - x86_64-linux
        test:
          - treefmt
          - clippy
          - deny
          - nextest
          - module-ipv4-only-test
          - module-ipv4-test
          - module-ipv6-only-test
          - module-ipv6-test
          - module-nginx-test
    env:
      TEST: ${{ matrix.test }}
      SYSTEM: ${{ matrix.system }}
    steps:
      - uses: https://git.salame.cl/actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - run: nix --version
      - name: Run tests
        run: |
          nix build --print-build-logs \
            .#checks."$SYSTEM"."$TEST"
  report-size:
    runs-on: nixos
    needs: build
    steps:
      - uses: https://git.salame.cl/actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - run: nix --version
      - name: Generate size report
        uses: "https://git.salame.cl/jalil/nix-flake-outputs-size@7a01dbeb0b8892cef331fc99995f3e554487c51b" # main
        with:
          comment-on-pr: ${{ github.ref_name != 'main' }}
          generate-artifact: ${{ github.ref_name == 'main' }}
          do-comparison: true
          job-name: report-size
