on: [push]
jobs:
  build:
    runs-on: nixos
    steps:
      - uses: https://git.salame.cl/actions/checkout@v4
      - run: nix --version
      - run: nix build --print-build-logs .#
  check:
    needs: build # we use the built binaries in the checks
    runs-on: nixos
    steps:
      - uses: https://git.salame.cl/actions/checkout@v4
      - run: nix --version
      - run: nix flake check --keep-going --verbose --print-build-logs
  report-size:
    runs-on: nixos
    needs: build
    steps:
      - uses: https://git.salame.cl/actions/checkout@v4
      - run: nix --version
      - name: Generate size report
        uses: https://git.salame.cl/jalil/nix-flake-outputs-size@main
        with:
          comment-on-pr: ${{ github.ref_name != 'main' }}
          generate-artifact: ${{ github.ref_name == 'main' }}
          do-comparison: true
          job-name: report-size
